services:
  db:
    container_name: postgres
    image: postgres:14

    environment:
      POSTGRES_USER: nazik
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  nazik-api:
    container_name: nazik-api
    image: jolygolden/nazik-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  nazik-react:
    container_name: nazik-react
    image: jolygolden/nazik-react
    build:
      context: frontend/react
    ports:
      - "3000:5173"
    depends_on:
      - nazik-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: